export const ConstraintsTypes = {
  'HORIZONTAL': 'HORIZONTAL',
  'LENGTH': 'LENGTH',
  'VERTICAL': 'VERTICAL',
  'FIX_POINT': 'FIX_POINT',
  'COINCIDENT': 'COINCIDENT',
  'PARALLEL': 'PARALLEL',
  'PERPENDICULAR':'PERPENDICULAR',
};